apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.ingress.name }}
  namespace: {{ .Values.namespace.collabora }}
  annotations:
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.tlsissuer }}
spec:
  rules:
  - host: {{ .Values.hosts.host }}
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.global.app.service.name }}
            port:
              number: 9980
  tls:
  - hosts:
    - {{ .Values.hosts.host }}
    secretName: {{ .Values.global.ingress.tlssecret }}
